# url: https://y7kim.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Paladin Ventures
# email: your-email@domain.com
description: "Paladin Ventures is the parent brand of several startup ventures founded by alumni of Cornell and Harvard University. These ventures range from an education startup with a #1 bestselling book to a software development consultancy."



# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
